server:
  port: 8090

spring:
  application:
    name: zuul-gateway

ribbon:
  ReadTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  ribbon:
    eager-load:
      enabled: true
  routes:
    group:
      sensitiveHeaders:
      path: group/**
      stripPrefix: false
      service-id: group
    reservation:
      sensitiveHeaders:
      path: reservation/**
      stripPrefix: false
      service-id: reservation
    room:
      sensitiveHeaders:
      path: room/**
      stripPrefix: false
      service-id: room
    user:
      sensitiveHeaders:
      path: user/**
      stripPrefix: false
      service-id: user
